# Install OCP installer and client
base_dir: "~/.ocp-install"
bin_dir: "{{ base_dir }}/bin"
ocp_install_dir: "{{ base_dir }}/ocp"
ocp_ci_release: "4.4.0-0.ci"
ocp_release: "latest"
ocp_rel_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp"
ocp_ci_api_rel_url: "https://openshift-release.svc.ci.openshift.org/api/v1/releasestream"
ocp_ci_rel_url: "https://openshift-release-artifacts.svc.ci.openshift.org"
get_release: true
get_ocp: true