# Install OCP cluster
base_dir: "~/.ocp-install"
bin_dir: "{{ base_dir }}/bin"
ocp_install_dir: "{{ base_dir }}/ocp"

# Cluster naming
cluster_name: "my-ocp-cluster"
cluster_dir:  "{{ base_dir }}/{{ cluster_name }}"
install_type: "gcp"

# AWS specific
aws_domain: "devcluster.openshift.com"
aws_region: "us-east-1"

# GCP specific
gcp_domain: "gcp.devcluster.openshift.com"
gcp_project_id: "openshift-gce-devel"
gcp_region: "us-east4"

# DNS Domain, pull secret, and ssh key paths
dns_domain: "{{ gcp_domain }}"
pull_secret_file: "~/.gcp/pull-secret.json"
ssh_key_file: "~/.ssh/id_rsa.pub"
ssh_key: "{{ lookup('file', ssh_key_file) }}"
get_release: true
create_cluster: true
kubeadmin: "kubeadmin"